In [1]:
#导入实验需要的包
from nes_py.wrappers import JoypadSpace
import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT

In [2]:
#使用gym_super_mario_bros包函数创建游戏环境env
env = gym_super_mario_bros.make('SuperMarioBros-v0')

C:\Users\losdeam\AppData\Roaming\Python\Python39\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment SuperMarioBros-v0 is out of date. You should consider upgrading to version `v3`.
  logger.warn(


In [4]:
#执行5000个简单的向右随机操作 
done = True #游戏结束标志
for step in range(2000):
    if done:
        #如果游戏结束则重置：
        state = env.reset() 
    action = env.action_space.sample()
    state, reward, done, truncated, info = env.step(action)
    print(env.step(2))
    print( )
    # state, reward, done, info = env.step(action)

ValueError: not enough values to unpack (expected 5, got 4)

In [10]:
#指定环境为简单模式（动作简化，去除一些左上、左下等复杂动作）
# env = JoypadSpace(env, SIMPLE_MOVEMENT)

In [10]:
#使用gym的wrapper函数对游戏视频进行录像（由于notebook不支持display，我们录像后播放观看）

from gym import wrappers
env=wrappers.RecordVideo(env,video_folder='',name_prefix='mario')

C:\Users\losdeam\AppData\Roaming\Python\Python39\site-packages\gym\wrappers\record_video.py:75: UserWarning: WARN: Overwriting existing videos at d:\learn\笔记\data\强化学习 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


C:\Users\losdeam\AppData\Roaming\Python\Python39\site-packages\gym\utils\passive_env_checker.py:195: UserWarning: WARN: The result returned by `env.reset()` was not a tuple of the form `(obs, info)`, where `obs` is a observation and `info` is a dictionary containing additional information. Actual type: `<class 'numpy.ndarray'>`
  logger.warn(
C:\Users\losdeam\AppData\Roaming\Python\Python39\site-packages\gym\utils\passive_env_checker.py:219: DeprecationWarning: WARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. 
  logger.deprecation(
C:\Users\losdeam\AppData\Roaming\Python\Python39\site-packages\gym\utils\passive_env_checker.py:225: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(done, (bool, np.bool8)):


ValueError: not enough values to unpack (expected 5, got 4)

In [ ]:
# 关闭创建的游戏env
env.close()

In [2]:
import io
import base64
from IPython.display import HTML

video = io.open('./gym-results/openaigym.video.%s.video000000.mp4' % env.file_infix, 'r+b').read()
encoded = base64.b64encode(video)
HTML(data='''
    <video width="360" height="auto" alt="test" controls><source src="data:video/mp4;base64,{0}" type="video/mp4" /></video>'''
.format(encoded.decode('ascii')))

NameError: name 'env' is not defined

In [1]:

import gym
from gym import envs

In [2]:
env_list = envs.registry.keys()
env_ids = [env_item for env_item in env_list]
# print('There are {0} envs in gym'.format(len(env_ids)))
# env_ids

There are 44 envs in gym


['CartPole-v0',
 'CartPole-v1',
 'MountainCar-v0',
 'MountainCarContinuous-v0',
 'Pendulum-v1',
 'Acrobot-v1',
 'LunarLander-v2',
 'LunarLanderContinuous-v2',
 'BipedalWalker-v3',
 'BipedalWalkerHardcore-v3',
 'CarRacing-v2',
 'Blackjack-v1',
 'FrozenLake-v1',
 'FrozenLake8x8-v1',
 'CliffWalking-v0',
 'Taxi-v3',
 'Reacher-v2',
 'Reacher-v4',
 'Pusher-v2',
 'Pusher-v4',
 'InvertedPendulum-v2',
 'InvertedPendulum-v4',
 'InvertedDoublePendulum-v2',
 'InvertedDoublePendulum-v4',
 'HalfCheetah-v2',
 'HalfCheetah-v3',
 'HalfCheetah-v4',
 'Hopper-v2',
 'Hopper-v3',
 'Hopper-v4',
 'Swimmer-v2',
 'Swimmer-v3',
 'Swimmer-v4',
 'Walker2d-v2',
 'Walker2d-v3',
 'Walker2d-v4',
 'Ant-v2',
 'Ant-v3',
 'Ant-v4',
 'Humanoid-v2',
 'Humanoid-v3',
 'Humanoid-v4',
 'HumanoidStandup-v2',
 'HumanoidStandup-v4']

In [3]:
env = gym.make('CartPole-v1')
print('观测空间 = {}'.format(env.observation_space))
print('动作空间 = {}'.format(env.action_space))
print('动作数 = {}'.format(env.action_space.n))
print('初始状态 = {}'.format(env.state))

观测空间 = Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
动作空间 = Discrete(2)
动作数 = 2
初始状态 = None


In [4]:
init_state = env.reset()
print('初始状态 = {}'.format(init_state))
print('初始状态 = {}'.format(env.state))

初始状态 = (array([0.032667  , 0.03133623, 0.04017115, 0.02277733], dtype=float32), {})
初始状态 = [0.032667   0.03133623 0.04017115 0.02277733]


In [8]:
for k in range(5):
    action = env.action_space.sample()
    print('*'*50)
    print(env.step(action))
    print('*'*50)
    state, reward, done, truncated, info = env.step(action)
    print('动作 = {0}: 当前状态 = {1}, 奖励 = {2}, 结束标志 = {3}, 日志信息 = {4}'.format(action, state, reward, done, info))

**************************************************
(array([ 0.2577957 , -0.72625476, -4.104528  , -7.418484  ], dtype=float32), 0.0, True, False, {})
(array([ 0.24327059, -0.86379784, -4.2528977 , -7.2949767 ], dtype=float32), 0.0, True, False, {})
**************************************************
(array([ 0.22599463, -0.998753  , -4.398797  , -7.1212482 ], dtype=float32), 0.0, True, False, {})
动作 = 0: 当前状态 = [ 0.20601958 -1.1336715  -4.541222   -6.904015  ], 奖励 = 0.0, 结束标志 = True, 日志信息 = {}
**************************************************
(array([ 0.18334615, -1.2708191 , -4.6793027 , -6.6493526 ], dtype=float32), 0.0, True, False, {})
(array([ 0.15792976, -1.4120334 , -4.8122897 , -6.3625207 ], dtype=float32), 0.0, True, False, {})
**************************************************
(array([ 0.1296891, -1.5586593, -4.93954  , -6.048051 ], dtype=float32), 0.0, True, False, {})
动作 = 0: 当前状态 = [ 0.09851591 -1.7115389  -5.060501   -5.70996   ], 奖励 = 0.0, 结束标志 = True, 日志信息 = {}
********