In [ ]:
import gym
env = gym.make("CartPole-v0")

In [ ]:
env.reset()

In [ ]:
print("env.action_space: ", env.action_space)

In [ ]:
#执行一个向左的操作
obj, reward, done, info = env.step(1) #1 向右 0向左
print("obj", obj) # 新状态
print("reward", reward) # 指定该动作获取的奖励值
print("done", done) # 回合是否结束
print("info", info) # 额外信息

In [ ]:
#随机获取一个动作
action = env.action_space.sample()
print(action)

In [14]:
env.reset()
done = True

for step in range(50):
    # if step % 100 == 0:
    
    #     print(step//100)
    # print(step)
    if done:
        state = env.reset()
    action = env.action_space.sample()
    state, reward, done, info = env.step(action)
    print(action)
    print(state)
    print("reward", reward) # 指定该动作获取的奖励值

env.close()


0
[-0.03358403 -0.20950812 -0.04158562  0.23245944]
reward 1.0
0
[-0.03777419 -0.40401195 -0.03693643  0.5117403 ]
reward 1.0
1
[-0.04585443 -0.20838972 -0.02670163  0.20765025]
reward 1.0
0
[-0.05002222 -0.40311988 -0.02254862  0.49179202]
reward 1.0
1
[-0.05808462 -0.20768724 -0.01271278  0.19208886]
reward 1.0
0
[-0.06223836 -0.40262505 -0.008871    0.48073448]
reward 1.0
1
[-0.07029087 -0.207379    0.00074368  0.18526889]
reward 1.0
0
[-0.07443845 -0.40251159  0.00444906  0.47818633]
reward 1.0
0
[-0.08248868 -0.59769607  0.01401279  0.77226818]
reward 1.0
0
[-0.0944426  -0.793008    0.02945815  1.06932693]
reward 1.0
0
[-0.11030276 -0.98850691  0.05084469  1.37110752]
reward 1.0
0
[-0.1300729  -1.18422659  0.07826684  1.67924954]
reward 1.0
0
[-0.15375743 -1.38016368  0.11185183  1.99524241]
reward 1.0
1
[-0.1813607  -1.18637565  0.15175668  1.73919272]
reward 1.0
1
[-0.20508821 -0.99327364  0.18654054  1.49731408]
reward 1.0
1
[-0.22495369 -0.80084396  0.21648682  1.26820247]
rew

In [1]:
import gym 
import torch
import torch.nn as nn 
import torch.nn.funtional as F


ModuleNotFoundError: No module named 'gym'